version: '3.1'
services:
  mysqldb:
    image: mysql
    container_name: 'lib-mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3308:3306"